// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/[username]/[repo]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[username]/[repo]">> = Specific
  const handler = {} as typeof import("../../app/[username]/[repo]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[username]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[username]">> = Specific
  const handler = {} as typeof import("../../app/[username]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/codespace/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/codespace/[sessionId]">> = Specific
  const handler = {} as typeof import("../../app/codespace/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/deploy-your-own/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/deploy-your-own">> = Specific
  const handler = {} as typeof import("../../app/deploy-your-own/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sessions/[sessionId]/chats/[chatId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sessions/[sessionId]/chats/[chatId]">> = Specific
  const handler = {} as typeof import("../../app/sessions/[sessionId]/chats/[chatId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sessions/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sessions/[sessionId]">> = Specific
  const handler = {} as typeof import("../../app/sessions/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sessions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sessions">> = Specific
  const handler = {} as typeof import("../../app/sessions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/accounts">> = Specific
  const handler = {} as typeof import("../../app/settings/accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/connections/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/connections">> = Specific
  const handler = {} as typeof import("../../app/settings/connections/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/leaderboard">> = Specific
  const handler = {} as typeof import("../../app/settings/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/model-variants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/model-variants">> = Specific
  const handler = {} as typeof import("../../app/settings/model-variants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/preferences/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/preferences">> = Specific
  const handler = {} as typeof import("../../app/settings/preferences/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/profile">> = Specific
  const handler = {} as typeof import("../../app/settings/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/usage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/usage">> = Specific
  const handler = {} as typeof import("../../app/settings/usage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/shared/[shareId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shared/[shareId]">> = Specific
  const handler = {} as typeof import("../../app/shared/[shareId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/u/[username]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/u/[username]">> = Specific
  const handler = {} as typeof import("../../app/u/[username]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[username]/og/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[username]/og">> = Specific
  const handler = {} as typeof import("../../app/[username]/og/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/github/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/github/callback">> = Specific
  const handler = {} as typeof import("../../app/api/auth/github/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/github/reconnect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/github/reconnect">> = Specific
  const handler = {} as typeof import("../../app/api/auth/github/reconnect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/github/unlink/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/github/unlink">> = Specific
  const handler = {} as typeof import("../../app/api/auth/github/unlink/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/info/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/info">> = Specific
  const handler = {} as typeof import("../../app/api/auth/info/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/signin/github/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signin/github">> = Specific
  const handler = {} as typeof import("../../app/api/auth/signin/github/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/signin/vercel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signin/vercel">> = Specific
  const handler = {} as typeof import("../../app/api/auth/signin/vercel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/signout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signout">> = Specific
  const handler = {} as typeof import("../../app/api/auth/signout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/vercel/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/vercel/callback">> = Specific
  const handler = {} as typeof import("../../app/api/auth/vercel/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chat/[chatId]/stop/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/[chatId]/stop">> = Specific
  const handler = {} as typeof import("../../app/api/chat/[chatId]/stop/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chat/[chatId]/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/[chatId]/stream">> = Specific
  const handler = {} as typeof import("../../app/api/chat/[chatId]/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/check-pr/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/check-pr">> = Specific
  const handler = {} as typeof import("../../app/api/check-pr/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/generate-pr/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate-pr">> = Specific
  const handler = {} as typeof import("../../app/api/generate-pr/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/generate-title/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate-title">> = Specific
  const handler = {} as typeof import("../../app/api/generate-title/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/git-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/git-status">> = Specific
  const handler = {} as typeof import("../../app/api/git-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/github/app/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/app/callback">> = Specific
  const handler = {} as typeof import("../../app/api/github/app/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/github/app/install/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/app/install">> = Specific
  const handler = {} as typeof import("../../app/api/github/app/install/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/github/branches/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/branches">> = Specific
  const handler = {} as typeof import("../../app/api/github/branches/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/github/connection-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/connection-status">> = Specific
  const handler = {} as typeof import("../../app/api/github/connection-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/github/create-repo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/create-repo">> = Specific
  const handler = {} as typeof import("../../app/api/github/create-repo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/github/installations/repos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/installations/repos">> = Specific
  const handler = {} as typeof import("../../app/api/github/installations/repos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/github/installations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/installations">> = Specific
  const handler = {} as typeof import("../../app/api/github/installations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/github/orgs/install-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/orgs/install-status">> = Specific
  const handler = {} as typeof import("../../app/api/github/orgs/install-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/github/orgs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/orgs">> = Specific
  const handler = {} as typeof import("../../app/api/github/orgs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/github/user/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/user">> = Specific
  const handler = {} as typeof import("../../app/api/github/user/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/github/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/webhook">> = Specific
  const handler = {} as typeof import("../../app/api/github/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/models/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/models">> = Specific
  const handler = {} as typeof import("../../app/api/models/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pr/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pr">> = Specific
  const handler = {} as typeof import("../../app/api/pr/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sandbox/activity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sandbox/activity">> = Specific
  const handler = {} as typeof import("../../app/api/sandbox/activity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sandbox/extend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sandbox/extend">> = Specific
  const handler = {} as typeof import("../../app/api/sandbox/extend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sandbox/reconnect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sandbox/reconnect">> = Specific
  const handler = {} as typeof import("../../app/api/sandbox/reconnect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sandbox/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sandbox">> = Specific
  const handler = {} as typeof import("../../app/api/sandbox/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sandbox/snapshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sandbox/snapshot">> = Specific
  const handler = {} as typeof import("../../app/api/sandbox/snapshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sandbox/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sandbox/status">> = Specific
  const handler = {} as typeof import("../../app/api/sandbox/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[sessionId]/chats/[chatId]/messages/[messageId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[sessionId]/chats/[chatId]/messages/[messageId]">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[sessionId]/chats/[chatId]/messages/[messageId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[sessionId]/chats/[chatId]/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[sessionId]/chats/[chatId]/messages">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[sessionId]/chats/[chatId]/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[sessionId]/chats/[chatId]/read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[sessionId]/chats/[chatId]/read">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[sessionId]/chats/[chatId]/read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[sessionId]/chats/[chatId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[sessionId]/chats/[chatId]">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[sessionId]/chats/[chatId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[sessionId]/chats/[chatId]/share/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[sessionId]/chats/[chatId]/share">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[sessionId]/chats/[chatId]/share/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[sessionId]/chats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[sessionId]/chats">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[sessionId]/chats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[sessionId]/checks/fix/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[sessionId]/checks/fix">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[sessionId]/checks/fix/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[sessionId]/close-pr/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[sessionId]/close-pr">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[sessionId]/close-pr/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[sessionId]/code-editor/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[sessionId]/code-editor">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[sessionId]/code-editor/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[sessionId]/dev-server/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[sessionId]/dev-server">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[sessionId]/dev-server/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[sessionId]/diff/cached/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[sessionId]/diff/cached">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[sessionId]/diff/cached/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[sessionId]/diff/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[sessionId]/diff">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[sessionId]/diff/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[sessionId]/files/content/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[sessionId]/files/content">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[sessionId]/files/content/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[sessionId]/files/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[sessionId]/files">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[sessionId]/files/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[sessionId]/generate-commit-message/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[sessionId]/generate-commit-message">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[sessionId]/generate-commit-message/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[sessionId]/merge-readiness/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[sessionId]/merge-readiness">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[sessionId]/merge-readiness/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[sessionId]/merge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[sessionId]/merge">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[sessionId]/merge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[sessionId]/pr-deployment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[sessionId]/pr-deployment">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[sessionId]/pr-deployment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[sessionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[sessionId]">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[sessionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[sessionId]/share/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[sessionId]/share">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[sessionId]/share/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[sessionId]/skills/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[sessionId]/skills">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[sessionId]/skills/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/model-variants/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/model-variants">> = Specific
  const handler = {} as typeof import("../../app/api/settings/model-variants/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/preferences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/preferences">> = Specific
  const handler = {} as typeof import("../../app/api/settings/preferences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shared/[shareId]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shared/[shareId]/status">> = Specific
  const handler = {} as typeof import("../../app/api/shared/[shareId]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/transcribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/transcribe">> = Specific
  const handler = {} as typeof import("../../app/api/transcribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/usage/rank/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/usage/rank">> = Specific
  const handler = {} as typeof import("../../app/api/usage/rank/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/usage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/usage">> = Specific
  const handler = {} as typeof import("../../app/api/usage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/vercel/projects/[idOrName]/env/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vercel/projects/[idOrName]/env">> = Specific
  const handler = {} as typeof import("../../app/api/vercel/projects/[idOrName]/env/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/vercel/repo-projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vercel/repo-projects">> = Specific
  const handler = {} as typeof import("../../app/api/vercel/repo-projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/u/[username]/og/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/u/[username]/og">> = Specific
  const handler = {} as typeof import("../../app/u/[username]/og/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/codespace/[sessionId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/codespace/[sessionId]">> = Specific
  const handler = {} as typeof import("../../app/codespace/[sessionId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sessions/[sessionId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/sessions/[sessionId]">> = Specific
  const handler = {} as typeof import("../../app/sessions/[sessionId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sessions/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/sessions">> = Specific
  const handler = {} as typeof import("../../app/sessions/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
